apiVersion: v1
kind: Pod
metadata:
  name: rook-ceph-playground
  namespace: rook-ceph-skyhookdm
spec:
  restartPolicy: Always
  containers:
    - name: rook-ceph-playground
      image: uccross/skyhookdm-arrow:v0.1.1
      securityContext:
        privileged: true
      command: ["sleep", "infinity"]
